### ISSUE TITLE
Control of acceleration. "Decided"

### ISSUE THREAD

**Issue by Ukol1** [marazmista/radeon-profile#153]
Thank you very much for the AMD graphics program. I use Manjaro Linux x86_64 Gnome version 2019.06.03. Gnome does not fully control the panel as it does for KDE.
On the overclocking tab : GPU overclocking works, memory does not work. When you select Manual frequency control, the change sliders do not work, States table is not active.
P.S Sorry for the translation.
![1](https://user-images.githubusercontent.com/30598904/63437841-88ecdf00-c455-11e9-9e8c-4c56284aec8f.png)
![Снимок экрана от 2019-08-21 20-21-58](https://user-images.githubusercontent.com/30598904/63437873-973afb00-c455-11e9-981b-30e2113d6095.png)
![Снимок экрана от 2019-08-21 20-56-13](https://user-images.githubusercontent.com/30598904/63438247-3102a800-c456-11e9-87c2-8cd134b05921.png)

**Comment by marazmista** [comment]
Hi, some info about manual frequency control: https://github.com/marazmista/radeon-profile/issues/137

About the states table being disabled, I see that you have mobile version of card, do you have `pp_od_clk_voltage` file in `/sys/class/drm/card0/device/`?

Also your core clock look odd but I'm not sure what cause that.

**Comment by Ukol1** [comment]
I don't have that file. The frequency of the GPU depend on the inclusion of acceleration.
![Снимок экрана от 2019-08-22 06-24-50](https://user-images.githubusercontent.com/30598904/63475145-e577ea80-c4a5-11e9-9a53-178a3a7e7dab.png)
![Снимок экрана от 2019-08-22 06-25-28](https://user-images.githubusercontent.com/30598904/63475152-eb6dcb80-c4a5-11e9-8fa0-c4591c7450a2.png)

**Comment by Ukol1** [comment]
I loaded a LiveCD of Ubuntu 18.10. There is a version of the program 2018.10.28, it's a simple comparison for overclocking the video card. There I, too, such a file not found.
![Снимок экрана от 2019-08-22 03-02-55](https://user-images.githubusercontent.com/30598904/63476669-2bd04800-c4ac-11e9-98d6-c2ca5e7bb6e4.png)
![Снимок экрана от 2019-08-22 03-00-19](https://user-images.githubusercontent.com/30598904/63476676-3094fc00-c4ac-11e9-8276-ff6db7edaf14.png)

**Comment by marazmista** [comment]
If you don't have this file, States table won't work.
I've pushed implementation of Manual frequency control: 9a364be47b751165504362b49b38d011c6712636

**Comment by Ukol1** [comment]
Hey. Good job. I checked all the GPU overclocking modes they work. Memory overclocking still doesn't work for me. When you change the slider in the file pp_mclk_od changes occur.
![Снимок экрана от 2019-08-26 02-38-03](https://user-images.githubusercontent.com/30598904/63665659-71677a80-c7f6-11e9-8a3f-bb92a75634d2.png)
![Снимок экрана от 2019-08-26 11-40-23](https://user-images.githubusercontent.com/30598904/63665667-77f5f200-c7f6-11e9-8301-a988f813580d.png)

**Comment by marazmista** [comment]
Does memory overclock work if you change it by hand from console?

**Comment by Ukol1** [comment]
Yes if you change the value in pp_mclk_od, the changes are applied after you restart value becomes the default.

**Comment by Ukol1** [comment]
Hello again. Is it possible to add a separate power management?! I have auto, high performance or manual, the power rises to 1.2 volts, artefacts appear or even the image is gone. When you choose low power 0.9 volts, the card works fine but no performance, frequency I cannot change. Any thoughts on downvoting your graphics card?

**Comment by Ukol1** [comment]
Hey. Here's a picture where I showed what works or doesn't work correctly. Does not change the memory frequency, constantly on default settings 945MHz.
![Снимок экрана от 2019-08-28 12-25-18](https://user-images.githubusercontent.com/30598904/63830751-1de06280-c997-11e9-8e69-882bcdcc5274.png)

**Comment by marazmista** [comment]
Memory overclock fixed in 93fb5cb12069bc0a0531cbc007462b5f7833b53b and values in table update 519703783aa1ad38dd04aa922a45b4106683b13f

**Comment by Ukol1** [comment]
Hi you did a great job! Everything works as it should. Attach screenshots. Thanks again!
![Снимок экрана от 2019-08-30 03-25-46](https://user-images.githubusercontent.com/30598904/63974266-b7625e00-cad6-11e9-9cda-a2bce8545140.png)
![Снимок экрана от 2019-08-30 03-27-26](https://user-images.githubusercontent.com/30598904/63974311-ce08b500-cad6-11e9-8783-9a322f7b9c7b.png)

**Comment by Ukol1** [comment]
Hi! Have a request, when you update the package to change the numbering of the Assembly. My main system Rosa Fresh R11 Plasma. Everything works fine. Thanks!
![3](https://user-images.githubusercontent.com/30598904/63999445-aa248e00-cb2d-11e9-8acd-20a3f24c6194.png)
![2](https://user-images.githubusercontent.com/30598904/63999449-ae50ab80-cb2d-11e9-80db-a32ab14f3501.png)

**Comment by marazmista** [comment]
Thanks for testing.

**Comment by Ukol1** [comment]
Thank you for the program! Keep up the good work!
